<script lang="ts">
  import { onMount } from "svelte";
  import { api, type AppConfig } from "../lib/api";
  import { refreshGreeting } from "../lib/state.svelte";

  let cfg = $state<AppConfig>({ displayName: "", zip: "", greetingEnabled: true });
  let settingsText = $state("");
  let claudeMd = $state("");
  let status = $state<Record<string, { ok: boolean; msg: string } | null>>({});

  onMount(async () => {
    const [c, s, m] = await Promise.allSettled([api.appConfig(), api.settingsText(), api.claudeMd()]);
    if (c.status === "fulfilled") cfg = c.value;
    if (s.status === "fulfilled") settingsText = s.value;
    if (m.status === "fulfilled") claudeMd = m.value;
  });

  function flash(key: string, ok: boolean, msg: string) {
    status[key] = { ok, msg };
    setTimeout(() => status[key] = null, 3500);
  }

  async function saveGreeting() {
    try {
      cfg = await api.saveAppConfig(cfg);
      flash("greeting", true, "saved");
      refreshGreeting();
    } catch (e) { flash("greeting", false, String(e)); }
  }
  async function saveSettings() {
    try {
      JSON.parse(settingsText);
    } catch { flash("settings", false, "invalid JSON — not saved"); return; }
    try {
      await api.saveSettingsText(settingsText);
      flash("settings", true, "saved — applies to new sessions");
    } catch (e) { flash("settings", false, String(e)); }
  }
  async function saveMd() {
    try {
      await api.saveClaudeMd(claudeMd);
      flash("md", true, "saved — applies to new sessions");
    } catch (e) { flash("md", false, String(e)); }
  }
</script>

<div class="greet-row">
  <div class="greet"><h1>Config</h1></div>
</div>

<div class="cfg-grid">
  <div class="glass glow cfg-card">
    <h3>Greeting</h3>
    <div class="cfg-row">
      <label for="cfg-name">Display name</label>
      <input id="cfg-name" type="text" bind:value={cfg.displayName} placeholder="Fenn" />
    </div>
    <div class="cfg-row">
      <label for="cfg-zip">Zip code (for weather)</label>
      <input id="cfg-zip" type="text" bind:value={cfg.zip} placeholder="97201" />
    </div>
    <label class="cfg-check">
      <input type="checkbox" bind:checked={cfg.greetingEnabled} />
      Whimsical greeting line (generated by Haiku, refreshed hourly)
    </label>
    <button class="btn" onclick={saveGreeting}>Save</button>
    {#if status.greeting}<span class="cfg-status" class:ok={status.greeting.ok} class:bad={!status.greeting.ok}>{status.greeting.msg}</span>{/if}
  </div>

  <div class="glass glow cfg-card">
    <h3>~/.claude/settings.json</h3>
    <textarea class="cfg-editor" bind:value={settingsText} spellcheck="false"></textarea>
    <button class="btn" onclick={saveSettings}>Save settings</button>
    {#if status.settings}<span class="cfg-status" class:ok={status.settings.ok} class:bad={!status.settings.ok}>{status.settings.msg}</span>{/if}
  </div>

  <div class="glass glow cfg-card cfg-full">
    <h3>~/.claude/CLAUDE.md</h3>
    <textarea class="cfg-editor" style="min-height:380px" bind:value={claudeMd} spellcheck="false"></textarea>
    <button class="btn" onclick={saveMd}>Save CLAUDE.md</button>
    {#if status.md}<span class="cfg-status" class:ok={status.md.ok} class:bad={!status.md.ok}>{status.md.msg}</span>{/if}
  </div>
</div>
